main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('sign-up', views.sign_up, name='sign_up'),
    path('create-post', views.create_post, name='create_post'),
    path('update_post/<int:post_id>/', views.update_post, name='update_post'),
    path('entries/<int:post_id>/', views.entries, name='entries'),
    path('create_entry/<int:post_id>/', views.create_entry, name='create_entry'),
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='delete_entry'),
    path('update_entry/<int:entry_id>/', views.update_entry, name='update_entry')
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('',include('django.contrib.auth.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='images/', null=True, blank=True) 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title + "\n" + self.description
    
class Entry(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
          return f"Entry {self.id}"

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post, Entry

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["email","username", "password1", "password2"]

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description", "image"]

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["description", "image"]

main/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, PostForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from .models import Post, Entry


@login_required(login_url="/login")
def home(request):
    posts = Post.objects.all()
    if request.method == 'POST':
        post_id = request.POST.get('post-id')
        post = Post.objects.filter(id=post_id).first()
        if post and post.author == request.user:
            post.delete()
    return render(request, 'main/home.html', {"posts": posts})


@login_required(login_url="/login")
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('/home')
    return render(request, 'main/create_post.html')


@login_required(login_url="/login")
def update_post(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.method == 'POST':
        post_form = PostForm(request.POST, request.FILES, instance=post)
        if post_form.is_valid():
            # post = post_form.save(commit=False)
            # post.author = request.user
            # post.save()
            post_form.save()
            return redirect('/home')
    return render(request, 'main/create_post.html', {"post": post})


@login_required(login_url="/login")
def entries(request, post_id):
    post = Post.objects.get(id=post_id)
    entries = Entry.objects.filter(post_id=post_id)
    return render(request, 'main/entries.html', {"post": post, "entries": entries})


@login_required(login_url="/login")
def create_entry(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.method == 'POST':
        entryForm = EntryForm(request.POST, request.FILES)
        if entryForm.is_valid():
            entry = entryForm.save(commit=False)
            entry.post = post
            entry.author = request.user
            entry.save()
        return redirect(f'/entries/{post_id}')
    else:
        print('here')
        entryForm = EntryForm()
    return render(request, 'main/create_entry.html', {"post": post})


@login_required(login_url="/login")
def delete_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    if entry and entry.author == request.user:
        entry.delete()
    entries = Entry.objects.filter(post_id=entry.post_id)
    post = Post.objects.get(id=entry.post_id)
    return render(request, 'main/entries.html', {"post": post, "entries": entries})


@login_required(login_url="/login")
def update_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    post = Post.objects.get(id=entry.post_id)
    if request.method == 'POST':
        entry_form = EntryForm(request.POST, request.FILES, instance=entry)
        if entry_form.is_valid():
            entry_form.save()
            entries = Entry.objects.filter(post_id=post.id)
            return render(request, 'main/entries.html', {"post": post, "entries": entries})
    return render(request, 'main/create_entry.html', {"post": post, "entry": entry})


def sign_up(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/home')
    else:
        form = RegisterForm()

    return render(request, 'registration/sign_up.html', {"form": form})

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>{% block title %}My site{% endblock %}</title>
    {% block style %}{% endblock style %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/create-post">Create Post</a>
                    </li>
                </ul>
            </div>
            <div>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <span class="navbar-text">Logged in as {{user.username}} |</span>
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/login">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {%block content%}
        {%endblock%}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>

main/templates/main/create_entry.html
{% extends "main/base.html" %}
{% block title %}Create Entry{% endblock title %}
{% block content %}
<h1>Create Entry</h1>
<p>{{entry.description}}</p>
{% if entry%}
<form enctype="multipart/form-data" action="{% url 'main:update_entry' entry.id %}" method="post">
{% else %}
<form enctype="multipart/form-data" action="{% url 'main:create_entry' post.id %}" method="post">
{% endif %}
{% csrf_token %}
    <div class="mb-5">
      <label class="form-label">Entry picture</label>
      <input class="form-control" name="image" type="file" id="formFile" onchange="preview()">
      <button type="button" onclick="clearImage()" class="btn btn-danger mt-3">Remove</button>
  </div>
  {% if entry.image %}
  <img id="frame" src={{entry.image.url}} class="img-fluid" />
  {% else %}
  <img id="frame" src="" class="img-fluid" />
  {% endif %}

    <div class="mb-3">
        <label >Description</label>
        {% if entry.description %}
        <textarea name="description" class="form-control">{{entry.description}}</textarea>
        {% else %}
        <textarea name="description" class="form-control"></textarea>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-success">Create Entry</button>
  </form>
  <script>
    function preview() {
        frame.src = URL.createObjectURL(event.target.files[0]);
    }
    function clearImage() {
        document.getElementById('formFile').value = null;
        frame.src = "";
        
    }
</script>
{% endblock content %}

main/templates/main/create_post.html
{% extends "main/base.html" %}
{% block title %}Create a Post{% endblock title %}
{% block content %}
{% if post %}
<form enctype="multipart/form-data" action="{% url 'main:update_post' post.id %}" method="post">
{% else %}
<form enctype="multipart/form-data" action="{% url 'main:create_post' %}" method="post">
{% endif %}
    {% csrf_token %}
    <div class="mb-5">
      <label class="form-label">Cover picture</label>
      <input class="form-control" name="image" type="file" id="formFile" onchange="preview()">
      <button type="button" onclick="clearImage()" class="btn btn-danger mt-3">Remove</button>
  </div>
  {% if post.image %}
  <img id="frame" src="{{post.image.url}}" class="img-fluid" />
  {% else %}
  <img id="frame" src="" class="img-fluid" />
  {% endif %}
  
    <div class="mb-3">
      <label class="form-label">Title</label>
      {% if post %}
      <input name="title" type="text" class="form-control" value={{post.title}}>
      {% else %}
      <input name="title" type="text" class="form-control">
      {% endif %}

    </div>
    <div class="mb-3">
      <label >Description</label>
      {% if post %}
      <textarea name="description" class="form-control">{{post.description}}</textarea>
      {% else %}
      <textarea name="description" class="form-control"></textarea>
      {% endif %}    
    </div>
    <button type="submit" class="btn btn-success">Post</button>
  </form>
  <script>
    function preview() {
        frame.src = URL.createObjectURL(event.target.files[0]);
    }
    function clearImage() {
        document.getElementById('formFile').value = null;
        frame.src = "";
        
    }
</script>
{% endblock content %}

main/templates/main/entries.html
{% extends "main/base.html" %}
{% block title %}Entry Page{% endblock title %}
{% block content %}
<h1>Entry Page</h1>
{% if user == post.author %}
<a class="btn btn-success" href="{% url 'main:create_entry' post.id%}">Add entry</a>
{% endif %}
<div class="row">
    {% for entry in entries %}
        {% comment %} <h1>{{entry.description}}</h1> {% endcomment %}
        <div class="card col-sm-6 m-2 p-0" style="width: 18rem;">
            <img class="card-img-top" src="/media/{{entry.image}}" alt="Card image cap">
            <div class="card-body">
            <p class="card-text">{{entry.description}}</p>
            </div>
            <ul class="list-group list-group-flush">
            <li class="list-group-item">{{entry.created_at}}</li>
            </ul>
            <div class="card-body">
                {% if user == entry.author %}
                <form method="post" action="{% url 'main:delete_entry' entry.id %}" >
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" name="entry-id" value="{{entry.id}}">Delete</button>
                </form>
                <a href="{% url 'main:update_entry' entry.id%}" class="btn btn-primary">Edit entry</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

main/templates/main/home.html
{% extends "main/base.html" %}
{% block title %}Home Page{% endblock title %}
{% block style %}
{%load static%}
<link rel="stylesheet" href="{% static 'home/home.css' %}"> 
{% endblock style %}
{% block content %}
<h1>Home Page</h1>
<div class="row">
    {% for post in posts %}
        <div class="card col-sm-6 m-2 p-0" style="width: 18rem;">
            {% if post.image %}
                <img class="card-img-top" src="/media/{{post.image}}" alt="Card image cap">
            {% else %}
                <img class="card-img-top" src="/media/images/No-Image-Placeholder.svg.png" alt="Card image cap">
            {% endif %}
            
            <div class="card-body">
            <h5 class="card-title">{{post.title}}</h5>
            <p class="card-text">{{post.description}}</p>
            </div>
            <ul class="list-group list-group-flush">
            <li class="list-group-item">{{post.author.username}}</li>
            <li class="list-group-item">{{post.created_at}}</li>
            </ul>
            <div class="card-body">
                {% if user == post.author %}
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" name="post-id" value="{{post.id}}">Delete</button>
                    <a href="{% url 'main:update_post' post.id%}" class="btn btn-success">Edit</a>
                </form>
            {% endif %}
            <a href="{% url 'main:entries' post.id%}" class="btn btn-primary">See entries</a>
        
        </div>
    </div>
    {% empty %}
    <p>No post yet :( </p>
{% endfor %}
</div>
{% endblock content %}